name = "pool-table-site"
compatibility_date = "2024-12-27"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "kitos-tables-db"
database_id = "901201f0-c0ca-4ca8-93f7-cc52ba2ef618"

# R2 Storage binding
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "kitos-table-images"
